select * from customers;

--decode
select cust_name, decode(cust_name,'hello',1,2)as m from customers;
select * from (select cust_name, decode(cust_name,'hello',1,2)as m from customers ) where m<>2;

--mod
select * from customers where mod(cust_id,2)<>0;

--rownum
select * from customers where rownum<3;

--row_number
select * from (select cust_name,row_number() over(order by cust_name)as r from customers) where mod(r,2)<>0;

--giving access to assecing the session to other session
create user mano identified by admin123;
alter session set "_ORACLE_SCRIPT"=true;
GRANT CREATE SESSION TO mano;
GRANT SELECT ON CUSTOMERS TO mano;

--lead&lag
create table custom(
id int generated by default as identity,
name varchar(30),
sales int,
year int
);

insert into custom(name,sales,year) values ('A',300,2020);
insert into custom(name,sales,year) values ('B',350,2023);
insert into custom(name,sales,year) values ('C',320,2022);
select * from custom;

--lead
select name,sales, lead(sales) over(order by sales)from custom;
select name,sales,year, lead(sales) over(order by year)from custom;

--lag
select name,sales, lag(sales) over(order by sales)from custom;

--swaping by lead&lag
select * from products;

select prod_id, case when mod(row_number() over (order by prod_id),2)<>0 then
lead(prod_name) over (order by prod_id) else
lag(prod_name) over (order by prod_id)end as m from products;

